version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - bencevans
  ignore:
  - dependency-name: redis
    versions:
    - 3.1.0
    - 3.1.1
  - dependency-name: slonik
    versions:
    - 23.5.5
    - 23.6.0
    - 23.6.2
    - 23.6.3
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
